name: auto_release
on:
  push:
    branches:
      - main
jobs:
  releaser:
    runs-on: ubuntu-22.04
    steps:
      - run: |
          touch App.tar.gz
          tar --exclude=App.tar.gz -zcvf Apps.tar.gz ./
      # - name: Create Release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      #   with:
      #     tag_name: "test-tag-name"
      #     release_name: Release "test-release"
      #     body: |
      #       Changes in this Release
      #       - First Change
      #       - Second Change

      #     draft: false
      #     prerelease: false
      - name: Create Release
        uses: djnicholson/release-action@v2.11
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag_name: "test-tag-name"
          release_name: Release "test-release"
          asset-name: 'Apps.tar.gz'
          file: './Apps.tar.gz'
